### PR TITLE
Port to osx arm64

### PR DESCRIPTION
**Pull request by jonashaag**
Closes #5

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Comment by martin-g** [comment]
@conda-forge/core Could someone please help with the review of this PR ? Thank you!

**Comment by wolfv** [comment]
@martin-g can you add yourself to the maintainers? Happy to merge then :)

**Comment by martin-g** [comment]
@wolfv I am not the author of this PR.
I could add myself in another PR. Would that be OK ? Then I can handle this PR and #5 and #7 !

**Comment by jonashaag** [comment]
I'll add you

**Review by wolfv — APPROVED** [review]

**Comment by wolfv** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Will merge after rerender! Thanks @martin-g!

**Comment by martin-g** [comment]
Thank you both!

**Pull request merged**
